### ISSUE TITLE
issues loading blogs from direct link

### ISSUE THREAD

**Issue by ericcquachh** [davidbliu/pbl-portal-new#10]
https://www.youtube.com/watch?v=NCufqTrCkIY&feature=youtu.be

**Comment by davidbliu** [comment]
can you provide what shows up in console? 
did it ever work before?

**Comment by ericcquachh** [comment]
<img width="1437" alt="screen shot 2015-09-19 at 2 58 52 pm" src="https://cloud.githubusercontent.com/assets/6131656/9978377/203e7d4a-5edf-11e5-97e4-ad207a91d7c4.png">

not sure, didn't test until now
