### ISSUE TITLE
Scavenger Bugs

### ISSUE THREAD

**Issue by kzhang22** [davidbliu/pbl-portal-new#6]
UI Problems
- Uploading Photo should have a link [unintuitive to upload photos from main page]
- Remove Icons
- Page Header

Upload Photo
- Uploading 2 pictures destroys groups.

**Comment by davidbliu** [comment]
[ ] hours remaining is slightly incorrect
[ ] uploading large files doesn't work paperclip?

**Comment by davidbliu** [comment]
add a page to notify people if their submission was marked as bad
